### ISSUE TITLE
Store already connected and found devices better so they arent cleared or re-indexed during a refresh search

### ISSUE THREAD

**Issue by himwho** [Mach1Studios/m1-orientationmanager#9]
Certain devices are found and connected and can de-list while remaining connected due to the ID no longer broadcasting during connected state.

An example are some BLE devices that have a broadcast state for pairing and a connected state once paired, each hardware type might need a method for storing and checking for previously found devices

**Comment by himwho** [comment]
ideally store connected devices to be properly added and reindexed with the same index in a newly created list during the search step?

**Comment by himwho** [comment]
recent QA had a machine dropping its connection with a Serial device over time; forcing the user to disconnect and reconnect, likely solved/related by this enhancement

**Comment by TsarVul** [comment]
I think that the root of the issue is HardwareBLE::refreshDevices. After refresh, the device vector could be populated with a different ordering of devices, therefore stored indexes might not point to the same device post-refresh. 
Said vector could be replaced with 2 hash sets of device info structs. One for connected devices, one for connectable devices.

**Comment by himwho** [comment]
Resolved nicely here: https://github.com/Mach1Studios/m1-orientationmanager/commit/0b0b43fb002eaa1b9c98e082e6732fb650cfb5f6
